config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :cars, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = @car.bookings.new(booking_params)
    @booking.user = current_user

    if @booking.starts_at.nil? || @booking.ends_at.nil?
      redirect_to @car, notice: "The reservation could not be created. The start date and end date are required."
    elsif @booking.starts_at < Date.today
      redirect_to @car, notice: "The reservation could not be created. The start date must be in the future."
    elsif @booking.ends_at < @booking.starts_at
      redirect_to @car, notice: "The reservation could not be created. The end date must be after the start date."
    elsif @booking.save
      redirect_to @car, notice: "Reservation created successfully."
    else
      redirect_to @car, notice: "The reservation could not be created."
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all

    if params[:city].present? && params[:query].present?
      @cars = Car.where("address ILIKE ?", "%#{params[:city]}%")
        .where("brand ILIKE ?", "%#{params[:query]}%")
    elsif params[:city].present?
      @cars = Car.where("address ILIKE ?", "%#{params[:city]}%")
    elsif params[:query].present?
      @cars = Car.where("brand ILIKE ?", "%#{params[:query]}%")
    end
  end

  def show
    @car = Car.find(params[:id])
    @bookings = @car.bookings
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<%# SEARCH %>
<div class="container py-3">
  <%= simple_form_for :search, url: cars_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <%= text_field_tag :city,params[:city],class: "d-none"%>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control string required",
          placeholder: "Brand.. Ex: Seat"
      %>
      <button type="submit" class="btn btn-flat">
          <i class="fas fa-search text-dark"></i><span class="text-dark">Search</span>
      </button>
    </div>
  <% end %>

  <%# CARD LISTE %>
  <div class="row justify-content-md-center">
    <% @cars.each do |car| %>
      <div class="col-3 m-3 bg-white rounded p-3 shadow">
        <div class="img-container">
          <img src="<%= [
            'https://images.caradisiac.com/logos/1/1/0/6/191106/S7-maxi-fiche-fiabilite-que-vaut-la-seat-ibiza-5-en-occasion-108185.jpg',
            'https://cdn-s-www.ledauphine.com/images/3941B2AB-35A8-403F-9AE0-2B79E7B9314A/NW_raw/des-jupes-laterales-specifiques-en-carbone-ont-ete-integrees-sur-l-alpine-a110-r-pour-etendre-le-plancher-plat-vers-l-exterieur-grace-a-cette-surface-prolongee-l-air-devient-moins-turbulent-tout-le-long-de-la-voiture-en-limitant-les-perturbations-dans-le-soubassement-1674482616.jpg',
            'https://www.largus.fr/images/images/205-gti-avd.jpg'
          ][car.price_per_day.to_i%3]%>"
          class="rounded-top img-fluid justify-content-center" width=300>
          <div class="badge">
            <%= car.price_per_day %>€/day
          </div>
        </div>
        <%= link_to car_path(car), class:"text-decoration-none" do %>
          <div class="card-title">
            <p class="brand"><%= car.brand %></p>
            <p class="model"><%= car.model %></p>
          </div>
          <div class="info">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-cake"><path d="M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8"/><path d="M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1"/><path d="M2 21h20"/><path d="M7 8v3"/><path d="M12 8v3"/><path d="M17 8v3"/><path d="M7 4h0.01"/><path d="M12 4h0.01"/><path d="M17 4h0.01"/></svg>
            <p><%= car.year_of_production %></p>
          </div>
          <div class="info">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pinned"><path d="M18 8c0 4.5-6 9-6 9s-6-4.5-6-9a6 6 0 0 1 12 0"/><circle cx="12" cy="8" r="2"/><path d="M8.835 14H5a1 1 0 0 0-.9.7l-2 6c-.1.1-.1.2-.1.3 0 .6.4 1 1 1h18c.6 0 1-.4 1-1 0-.1 0-.2-.1-.3l-2-6a1 1 0 0 0-.9-.7h-3.835"/></svg>
            <p><%= car.address %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<%# CARD %>
<div class="container py-3">
  <%= link_to "Back", cars_path, class: "custom-btn btn-2" %>
  <div class="row justify-content-center">
    <div class="col m-3 bg-white rounded p-3 shadow">
      <div style="display:flex; width:100%; place-content:center;">
        <img src="<%= [
          'https://images.caradisiac.com/logos/1/1/0/6/191106/S7-maxi-fiche-fiabilite-que-vaut-la-seat-ibiza-5-en-occasion-108185.jpg',
          'https://cdn-s-www.ledauphine.com/images/3941B2AB-35A8-403F-9AE0-2B79E7B9314A/NW_raw/des-jupes-laterales-specifiques-en-carbone-ont-ete-integrees-sur-l-alpine-a110-r-pour-etendre-le-plancher-plat-vers-l-exterieur-grace-a-cette-surface-prolongee-l-air-devient-moins-turbulent-tout-le-long-de-la-voiture-en-limitant-les-perturbations-dans-le-soubassement-1674482616.jpg',
          'https://www.largus.fr/images/images/205-gti-avd.jpg'
        ][@car.price_per_day.to_i%3]%>"
        class="rounded-top img-fluid justify-content-center" width=300>
      </div>
      <h2 class="text-center p-2"><%= @car.brand %> <%= @car.model %></h2>
      <div class="d-flex justify-content-center" style="gap: 20px;">
        <p>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-cake"><path d="M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8"/><path d="M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1"/><path d="M2 21h20"/><path d="M7 8v3"/><path d="M12 8v3"/><path d="M17 8v3"/><path d="M7 4h0.01"/><path d="M12 4h0.01"/><path d="M17 4h0.01"/></svg>
          <%= @car.year_of_production %></p>
        <p>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>
          <%= @car.address %></p>
        <p>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-badge-euro"><path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"/><path d="M7 12h5"/><path d="M15 9.4a4 4 0 1 0 0 5.2"/></svg>
          <%= @car.price_per_day %>/day
        </p>
      </div>
      <p><strong>Comment:</strong> <%= @car.comment %></p>
    </div>

    <%# FORMULAIRE %>
    <div class="col m-3 bg-white rounded p-3 shadow" >
      <h1 class="text-center mt-3">Reservation</h1>
      <div style="align-content: center; width:100%; height:100%">
        <%= simple_form_for([@car, @booking]) do |form| %>
          <%= form.input :starts_at,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
          <%= form.input :ends_at,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
            <%= form.submit "Book", class: 'custom-btn btn-1'%>
        <% end %>
      </div>
    </div>
  </div>

  <%# TABLE BOOKINGS %>
  <div class="row justify-content-center">
    <div class="col m-3 bg-white rounded p-3 shadow">
      <h1 class="text-center mt-3">Bookings</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Starts at</th>
            <th>Ends at</th>
          </tr>
        </thead>
        <tbody>
          <% @car.bookings.each do |booking| %>
            <tr>
              <td><%= booking.starts_at %></td>
              <td><%= booking.ends_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn-s-www.ledauphine.com/images/3941B2AB-35A8-403F-9AE0-2B79E7B9314A/NW_raw/des-jupes-laterales-specifiques-en-carbone-ont-ete-integrees-sur-l-alpine-a110-r-pour-etendre-le-plancher-plat-vers-l-exterieur-grace-a-cette-surface-prolongee-l-air-devient-moins-turbulent-tout-le-long-de-la-voiture-en-limitant-les-perturbations-dans-le-soubassement-1674482616.jpg);">
  <div class="container">
    <h1><strong>CAR RENTAL<strong> Book a car now and enjoy easy travels !</h1>
    <p>Explore new horizons with our wide range of available cars.</p>

    <div class="row">
      <div class="col-4">
        <%= simple_form_for :search, url: cars_path, method: :get do |f| %>
          <div class="search-form-control form-group">

            <%= text_field_tag :city,
                params[:city],
                class: "form-control string required",
                placeholder: "City ex : Rennes"
            %>
            <button name="button" type="submit" class="btn btn-flat">
                <i class="fas fa-search text-dark"></i><span class="text-dark">Search</span>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://img.freepik.com/vecteurs-libre/vecteur-degrade-logo-colore-oiseau_343694-1365.jpg?size=338&ext=jpg&ga=GA1.1.87170709.1711497600&semt=sph" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>